# Universal "kill" action for our self‑hosted micro‑services.
# Intentionally simple: just cd into the service dir and run the stop script.
#
# NOTE:
#  * Works on both Linux and Windows (runner.os switch).
#  * No checkout, no extra deps – keep it lean.
name: universal-kill
inputs:
  dir:
    description: relative path to service directory
    required: true
  stop:
    description: command that stops the service (bash or bat)
    required: true
runs:
  using: composite
  steps:
    - shell: ${{ runner.os == 'Windows' && 'cmd' || 'bash' }}
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.stop }}
