name: universal-start
inputs:
  dir:
    description: relative path to service directory
    required: true
  copy:
    description: command that places application.properties
    required: true
  start:
    description: command that starts the service
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with: 
        ref: ${{ github.sha }} 
        fetch-depth: 0 
        clean: true 
        lfs: true

    # copy config; if path changes in the future, tweak matrix not here
    - shell: ${{ runner.os == 'Windows' && 'cmd' || 'bash' }}
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.copy }}

    - shell: ${{ runner.os == 'Windows' && 'cmd' || 'bash' }}
      working-directory: ${{ inputs.dir }}
      run: ${{ inputs.start }}
