name: service-ops
on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      service:
        description: 'master | processor | scraper | all'
        default: all
        options: [ all, master, processor, scraper ]
        type: choice
      action:
        description: "kill | start | both"
        required: true
        default: both
        type: choice
        options:
          - kill
          - start
          - both
          
jobs:
  svc:
    strategy:
      matrix:
        include:
          - service: master
            dir: master-service
            stop: './man.sh stop'
            copy: 'cp "/opt/actions-runner/application.properties" "src/main/resources"'
            start: './man.sh start'
            runs: [ self-hosted, Linux, master ]
            
          - service: processor
            dir: processor-service
            stop: 'call killnow.bat'
            copy: 'copy "C:\actions-runner\application.properties" "src\main\resources\"'
            start: 'call bootnohup.bat'
            runs: [ self-hosted, Windows, processor ]
            
          - service: scraper
            dir: scraper-service
            stop: 'call killnow.bat'
            copy: 'copy "C:\actions-runner\application.properties" "src\main\resources\"'
            start: 'call bootnohup.bat'
            runs: [ self-hosted, Windows, scraper ]
    runs-on: ${{ matrix.runs }}

    # avoid overlapping restarts if several pushes land quickly
    concurrency:
      group: restart-${{ matrix.service }}
      cancel-in-progress: true

    env:
      ACTION: ${{ github.event_name == 'pull_request' && 'both' || github.event.inputs.action }}

    steps:
      - uses: actions/checkout@v4
        with: 
          ref: ${{ github.sha }} 
          fetch-depth: 0 
          clean: true 
          lfs: true
          
      - name: kill
        if: (env.ACTION == 'kill' || env.ACTION == 'both') &&
            (github.event_name == 'pull_request' ||
             github.event.inputs.service == 'all' ||
             github.event.inputs.service == matrix.service)

        uses: ./.github/actions/service-kill
        with:
          dir:  ${{ matrix.dir }}
          stop: ${{ matrix.stop }}

      - name: start
        if: (env.ACTION == 'start' || env.ACTION == 'both') &&
            (github.event_name == 'pull_request' ||
             github.event.inputs.service == 'all' ||
             github.event.inputs.service == matrix.service)

        uses: ./.github/actions/service-start
        with:
          dir:   ${{ matrix.dir }}
          copy:  ${{ matrix.copy }}
          start: ${{ matrix.start }}

# PR -> zawsze leci (wszystkie wiersze)
# ręcznie + all -> j.w.
# ręcznie + konkretny serwis -> filtrowanie